"""added start and end columns to task table2

Revision ID: 947596ff27df
Revises: 7cb4e1313f73
Create Date: 2024-07-23 15:14:09.388491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947596ff27df'
down_revision = '7cb4e1313f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_months')
    with op.batch_alter_table('months', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('end')
        batch_op.drop_column('start')

    with op.batch_alter_table('months', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_months',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('year_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], name='fk_months_year_id_years'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    # ### end Alembic commands ###
